library(shiny)
library(shinydashboard)
library(shinythemes)
library(shinyWidgets)
library(shinyBS)
library(shinyjs)
library(DT)
library(tidyverse)
library(tidytext)
library(fgsea)
library(data.table)
library(RColorBrewer)
library(plotly)
library(htmltools)
library(waiter)
library(shinyalert)
library(shinydisconnect)
library(rintrojs)

options(repos = BiocManager::repositories())

source("global/functions.R")
source("global/variables.R")
