if(!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
if (!require('shiny')) {install.packages('shiny')}
if (!require('shinydashboard')) {install.packages('shinydashboard')}
if (!require('shinydashboardPlus')) {install.packages('shinydashboardPlus')}
if (!require('shinythemes')) {install.packages('shinythemes')}
if (!require('shinyWidgets')) install.packages('shinyWidgets')
if (!require('shinyBS')) install.packages('shinyBS')
if (!require('shinyjs')) install.packages('shinyjs')
if (!require('DT')) install.packages('DT')
if (!require('tidyverse')) install.packages('tidyverse')
if (!require('tidytext')) install.packages('tidytext')
if (!require('fgsea')) BiocManager::install('fgsea')
if (!require('survival')) install.packages('survival')
if (!require('survminer')) install.packages('survminer')
if (!require('data.table')) install.packages('data.table')
if (!require('grid')) install.packages('grid')
if (!require('RColorBrewer')) install.packages('RColorBrewer')
if (!require('plotly')) install.packages('plotly')
if (!require('htmltools')) install.packages('htmltools')
if (!require('waiter')) install.packages('waiter')
if (!require('shinyalert')) install.packages('shinyalert')
if (!require('shinydisconnect')) install.packages('shinydisconnect')
if (!require('rintrojs')) install.packages('rintrojs')
# if (!require('edgeR')) BiocManager::install('edgeR')
# if (!require('limma')) BiocManager::install('limma')
if (!require('org.Hs.eg.db')) BiocManager::install('org.Hs.eg.db')
if (!require('ids')) install.packages('ids')
if (!require('pacman')) install.packages('pacman')
if (!require('colorspace')) install.packages('colorspace')
if (!require('ggsci')) install.packages('ggsci')
if (!require('plyr')) install.packages('plyr')
if (!require('parallel')) install.packages('parallel')
if (!require('stats')) install.packages('stats')
if (!require('shinybusy')) install.packages('shinybusy')

library(shiny)
library(shinydashboard)
library(shinydashboardPlus, include.only=c("boxPad","descriptionBlock")) # "appButton","box","loadingState"
library(shinythemes)
library(shinyWidgets)
library(shinyBS)
library(shinyjs)
library(DT)
library(tidyverse)
library(tidytext)
library(fgsea)
library(survival) # to do the survival analysis
library(survminer) # to plot the survival analysis nicer
library(data.table)
library(grid)
library(RColorBrewer)
library(plotly)
library(htmltools)
library(waiter)
library(shinyalert)
library(shinydisconnect)
library(rintrojs)
# library(edgeR)
# library(limma)
library(org.Hs.eg.db)
library(ids)
library(pacman)
library(colorspace)
library(ggsci)
library(plyr)
library(parallel)
library(stats)
# library(profvis)
library(shinybusy)
# library(arrangements) # permutations
options(repos = BiocManager::repositories())

source("global/functions.R")
source("global/variables.R")

# --------------- Initialize introjs -------------------
intropath <- paste0(getwd(), "/intro/")
filepaths <- list.files(intropath, full.names=T)
intros <- lapply(filepaths, function(x){
  df <- data.frame(read.csv(x, header=T, sep="\t"))
  df$element <- sub("^", "#", df$element)
  df[df=="#"] <- NA
  df
})
names(intros) <- tools::file_path_sans_ext(list.files(intropath, full.names=F))
rownames(intros) <- NULL
