library(shiny)
library(shinydashboard)
# library(shinydashboardPlus, include.only=c("appButton","box","boxPad","descriptionBlock","loadingState"))
library(shinythemes)
library(shinyWidgets)
library(shinyBS)
library(shinyjs)
library(DT)
library(tidyverse)
library(tidytext)
library(fgsea)
library(survival) # to do the survival analysis
library(survminer) # to plot the survival analysis nicer
library(data.table)
library(grid)
library(RColorBrewer)
library(plotly)
library(htmltools)
library(waiter)
library(shinyalert)
library(shinydisconnect)
library(rintrojs)

options(repos = BiocManager::repositories())

source("global/functions.R")
source("global/variables.R")
